set script_dir [file dirname [file normalize [info script]]]
set root_dir [file normalize [file join $script_dir ..]]
set build_dir [file join $root_dir build]
set report_dir [file join $root_dir reports]
set part_name "xcu250-figd2104-2L-e"
set clock_mhz 300.0
if {[info exists ::env(ATTENTION_CLOCK_MHZ)]} {
    if {![string is double -strict $::env(ATTENTION_CLOCK_MHZ)] ||
        $::env(ATTENTION_CLOCK_MHZ) <= 0.0} {
        error "ATTENTION_CLOCK_MHZ must be a positive number"
    }
    set clock_mhz [expr {double($::env(ATTENTION_CLOCK_MHZ))}]
}
set clock_ns [expr {1000.0 / $clock_mhz}]
set clock_tag "[format %.0f $clock_mhz]mhz"
set run_tag ""
if {[info exists ::env(ATTENTION_RUN_TAG)] && $::env(ATTENTION_RUN_TAG) ne ""} {
    set run_tag [string trim $::env(ATTENTION_RUN_TAG)]
    if {![regexp {^[A-Za-z0-9_-]+$} $run_tag]} {
        error "ATTENTION_RUN_TAG may contain only letters, digits, _ and -"
    }
}
set version "attention_v7_0_hls_timing_boundary_${clock_tag}"
if {$run_tag ne ""} {
    append version "_${run_tag}"
}
append version "_2026_07_13"

file mkdir $build_dir
file mkdir $report_dir

proc show_failure_logs {project_dir} {
    set db [file join $project_dir solution1 .autopilot db]
    foreach pattern [list "*clang*.err.log" "*.opt.err.log" "*.llvm-link.err.log"] {
        foreach path [glob -nocomplain [file join $db $pattern]] {
            if {[file size $path] > 0} {
                puts stderr "---- $path ----"
                set fh [open $path r]
                puts stderr [read $fh]
                close $fh
            }
        }
    }
    set flow [file join $db autopilot.flow.log]
    if {[file exists $flow] && [file size $flow] > 0} {
        set fh [open $flow r]
        set lines [split [read $fh] "\n"]
        close $fh
        puts stderr "---- autopilot.flow.log tail ----"
        foreach line [lrange $lines end-79 end] {
            puts stderr $line
        }
    }
}

proc copy_detailed_reports {project_dir top report_name} {
    global report_dir clock_tag run_tag
    set syn_report_dir [file join $project_dir solution1 syn report]

    # Vitis HLS 2022.1 writes the full hierarchy/loop/II/latency/resource table
    # shown in the GUI to csynth.rpt. Prefer it over the per-function report.
    set primary [file join $syn_report_dir csynth.rpt]
    if {![file exists $primary] || [file size $primary] == 0} {
        set primary [file join $syn_report_dir "${top}_csynth.rpt"]
    }
    if {![file exists $primary] || [file size $primary] == 0} {
        error "full csynth report is missing from $syn_report_dir"
    }

    set exported [file join $report_dir $report_name]
    file copy -force $primary $exported

    # Keep every module/loop report and machine-readable XML generated by HLS.
    set detail_dir [file join $report_dir details]
    if {$clock_tag ne "300mhz"} {
        set detail_dir [file join $detail_dir $clock_tag]
    }
    if {$run_tag ne ""} {
        set detail_dir [file join $detail_dir $run_tag]
    }
    set detail_dir [file join $detail_dir $top]
    file delete -force $detail_dir
    file mkdir $detail_dir
    foreach path [glob -nocomplain [file join $syn_report_dir *]] {
        if {[file isfile $path] && [file size $path] > 0} {
            file copy -force $path $detail_dir
        }
    }

    puts "Detailed summary: $exported ([file size $exported] bytes)"
    puts "All module reports: $detail_dir"
}

proc copy_rtl_synthesis_reports {project_dir top} {
    global report_dir clock_tag run_tag
    set impl_report_dir [file join $project_dir solution1 impl report]
    if {![file isdirectory $impl_report_dir]} {
        error "RTL synthesis report directory is missing: $impl_report_dir"
    }

    set exported [file join $report_dir rtl_syn]
    if {$clock_tag ne "300mhz"} {
        set exported [file join $exported $clock_tag]
    }
    if {$run_tag ne ""} {
        set exported [file join $exported $run_tag]
    }
    set exported [file join $exported $top]
    file delete -force $exported
    file mkdir [file dirname $exported]
    file copy -force $impl_report_dir $exported
    puts "RTL synthesis reports: $exported"
}

proc synth_kernel {top source report_name} {
    global root_dir build_dir report_dir part_name clock_ns clock_mhz clock_tag run_tag version
    set source_path [file join $root_dir kernels $source]
    set project_name "proj_${top}"
    if {$clock_tag ne "300mhz"} {
        append project_name "_${clock_tag}"
    }
    if {$run_tag ne ""} {
        append project_name "_${run_tag}"
    }
    set project_dir [file join $build_dir $project_name]

    puts "============================================================"
    puts "Script version: $version"
    puts "Kernel: $top"
    puts "Source: $source_path"
    puts "Clock: $clock_mhz MHz ($clock_ns ns)"
    puts "============================================================"

    set old_dir [pwd]
    set ok 1
    if {[catch {
        cd $build_dir
        open_project -reset $project_name
        add_files -cflags "-std=c++14 -I[file join $root_dir include]" $source_path
        set_top $top
        open_solution -reset solution1 -flow_target vivado
        set_part $part_name
        create_clock -period $clock_ns -name default
        csynth_design

        copy_detailed_reports $project_dir $top $report_name
        # Logic synthesis only: this does not run placement or routing. Run it
        # for every Attention kernel so 300 MHz decisions use real RTL timing
        # instead of comparing only against the conservative HLS scheduler
        # budget after default clock uncertainty.
        export_design -flow syn -rtl verilog
        copy_rtl_synthesis_reports $project_dir $top
    } message]} {
        puts stderr "ERROR: $top: $message"
        show_failure_logs $project_dir
        set ok 0
    }
    catch {close_project}
    cd $old_dir
    return $ok
}

array set source_for {
    bert_qkv_kernel bert_qkv_kernel.cpp
    bert_attn_core_kernel bert_attn_core_kernel.cpp
    bert_attn_out_norm_kernel bert_attn_out_norm_kernel.cpp
}
array set report_for {
    bert_qkv_kernel csynth_qkv.rpt
    bert_attn_core_kernel csynth_attn_core.rpt
    bert_attn_out_norm_kernel csynth_attn_out_norm.rpt
}

set all_kernels [list bert_qkv_kernel bert_attn_core_kernel bert_attn_out_norm_kernel]
set selected {}
if {[info exists ::env(ATTENTION_KERNELS)] && $::env(ATTENTION_KERNELS) ne ""} {
    foreach top [split $::env(ATTENTION_KERNELS) ","] {
        set top [string trim $top]
        if {![info exists source_for($top)]} {
            error "Unknown kernel in ATTENTION_KERNELS: $top"
        }
        lappend selected $top
    }
} else {
    foreach arg $argv {
        if {[info exists source_for($arg)]} {
            lappend selected $arg
        }
    }
}
if {[llength $selected] == 0} {
    set selected $all_kernels
}

set failed {}
foreach top $selected {
    set report_name $report_for($top)
    set report_suffix ""
    if {$clock_tag ne "300mhz"} {
        append report_suffix "_${clock_tag}"
    }
    if {$run_tag ne ""} {
        append report_suffix "_${run_tag}"
    }
    if {$report_suffix ne ""} {
        set report_name "[file rootname $report_name]${report_suffix}[file extension $report_name]"
    }
    if {[synth_kernel $top $source_for($top) $report_name]} {
        puts "PASS: $top"
    } else {
        puts "FAIL: $top"
        lappend failed $top
    }
}

puts "============================================================"
if {[llength $failed] == 0} {
    puts "ALL SELECTED ATTENTION KERNELS PASSED"
    exit 0
}
puts stderr "FAILED: [join $failed {, }]"
exit 1
